baseURL       = "/"
languageCode  = "en-us"
title         = "PyroCMS 3 Community Docs"
themesDir     = "themes"
theme         = "pyrocms-community-docs-theme"

[Params]
    gitPath   = "finnito/pyrocms-community-docs"

[markup.tableOfContents]
    endLevel = 4
[markup.highlight]
    style = "manni"
[markup.goldmark.renderer]
    unsafe    = true